import type { Project, Scene, Beat, Character, VariableValue } from '@ch5me/storygen-schema';
import {
  selectStory,
  gatherScenes,
  indexCharacters,
  requireCharacterName,
  type CompileOptions,
} from './internal/story-selection';
import { escapeDoubleQuoted, formatInkValue } from './internal/value-format';

/**
 * Ink requires every variable referenced by `~ x = ...` to be declared with
 * `VAR`. Collect the union of project variables plus any flags written by
 * state_change beats / choice option setFlags, so the emitted Ink always
 * declares everything it assigns and compiles cleanly.
 */
function collectVariables(project: Project, scenes: Scene[]): Map<string, VariableValue> {
  const vars = new Map<string, VariableValue>();
  for (const variable of project.variables) {
    vars.set(variable.key, variable.initial);
  }
  for (const scene of scenes) {
    for (const beat of scene.beats) {
      if (beat.kind === 'state_change') {
        for (const key of Object.keys(beat.set)) {
          if (!vars.has(key)) vars.set(key, defaultFor(beat.set[key]!));
        }
      }
      if (beat.kind === 'choice') {
        for (const option of beat.options) {
          if (!option.setFlags) continue;
          for (const key of Object.keys(option.setFlags)) {
            if (!vars.has(key)) vars.set(key, defaultFor(option.setFlags[key]!));
          }
        }
      }
    }
  }
  return vars;
}

/** A type-appropriate initial value when a flag is assigned but never declared. */
function defaultFor(value: VariableValue): VariableValue {
  if (typeof value === 'string') return '';
  if (typeof value === 'boolean') return false;
  return 0;
}

function emitBeat(beat: Beat, characters: Map<string, Character>): string[] {
  switch (beat.kind) {
    case 'narration':
      return [beat.text];
    case 'dialogue': {
      const name = requireCharacterName(characters, beat.characterId, beat.id);
      return [`${name}: ${beat.text}`];
    }
    case 'choice': {
      const lines: string[] = [];
      for (const option of beat.options) {
        lines.push(`* [${escapeDoubleQuoted(option.label)}]`);
        if (option.setFlags) {
          for (const key of Object.keys(option.setFlags).sort()) {
            lines.push(`    ~ ${key} = ${formatInkValue(option.setFlags[key]!)}`);
          }
        }
        lines.push(`    -> ${option.target}`);
      }
      return lines;
    }
    case 'state_change': {
      const lines: string[] = [];
      for (const key of Object.keys(beat.set).sort()) {
        lines.push(`~ ${key} = ${formatInkValue(beat.set[key]!)}`);
      }
      return lines;
    }
    case 'jump':
      return [`-> ${beat.target}`];
    // Canonical-only beats with no Ink rendering in v1.
    case 'stage':
    case 'panel_cue':
    case 'asset_event':
    case 'branch':
      return [];
    default: {
      const exhaustive: never = beat;
      throw new Error(`ink: unhandled beat kind: ${JSON.stringify(exhaustive)}`);
    }
  }
}

/**
 * A knot must terminate with a divert or choices. Determine whether the scene
 * already provides its own terminal control flow (a jump beat or a choice with
 * targets). If not, the scene must explicitly divert to its `next` scene or to
 * `END`.
 */
function sceneTerminates(scene: Scene): boolean {
  const last = scene.beats[scene.beats.length - 1];
  if (!last) return false;
  return last.kind === 'jump' || last.kind === 'choice';
}

function emitScene(scene: Scene, characters: Map<string, Character>): string[] {
  const lines: string[] = [`=== ${scene.id} ===`];
  for (const beat of scene.beats) {
    lines.push(...emitBeat(beat, characters));
  }
  if (!sceneTerminates(scene)) {
    lines.push(scene.next !== undefined ? `-> ${scene.next}` : '-> END');
  }
  return lines;
}

/**
 * Compile the canonical project into deterministic Ink source that compiles
 * cleanly under inkjs. Every assigned flag is declared via `VAR`, and every
 * knot terminates with a divert or choices.
 */
export function compileInk(project: Project, opts?: CompileOptions): string {
  const story = selectStory(project, opts);
  const characters = indexCharacters(project);
  const scenes = gatherScenes(story);
  const vars = collectVariables(project, scenes);

  const lines: string[] = [
    `// Ink export — generated by @ch5me/storygen-compiler`,
    `// Project: ${project.id} — Story: ${story.id} (${story.title})`,
    '',
  ];

  for (const [key, value] of vars) {
    lines.push(`VAR ${key} = ${formatInkValue(value)}`);
  }
  if (vars.size > 0) lines.push('');

  // Entrypoint diverts into the start scene.
  lines.push(`-> ${story.startSceneId}`);

  for (const scene of scenes) {
    lines.push('');
    lines.push(...emitScene(scene, characters));
  }

  return `${lines.join('\n')}\n`;
}
