import type { Project, Scene, Beat, Character } from '@ch5me/storygen-schema';
import {
  selectStory,
  gatherScenes,
  indexCharacters,
  requireCharacterName,
  type CompileOptions,
} from './internal/story-selection';
import { escapeDoubleQuoted, formatPythonValue } from './internal/value-format';

/** Stable Ren'Py character variable name for a world character id. */
function characterVar(characterId: string): string {
  return `char_${characterId}`;
}

function emitDefines(characters: Character[]): string[] {
  // Characters are already in authored order; deterministic by construction.
  return characters.map(
    (c) => `define ${characterVar(c.id)} = Character("${escapeDoubleQuoted(c.name)}")`,
  );
}

function emitBeat(beat: Beat, characters: Map<string, Character>): string[] {
  switch (beat.kind) {
    case 'narration':
      return [`    "${escapeDoubleQuoted(beat.text)}"`];
    case 'dialogue':
      // Reference the defined Character variable; name lookup validates the ref.
      requireCharacterName(characters, beat.characterId, beat.id);
      return [`    ${characterVar(beat.characterId)} "${escapeDoubleQuoted(beat.text)}"`];
    case 'choice': {
      const lines: string[] = ['    menu:'];
      if (beat.prompt !== undefined) {
        lines.push(`        "${escapeDoubleQuoted(beat.prompt)}"`);
      }
      for (const option of beat.options) {
        lines.push(`        "${escapeDoubleQuoted(option.label)}":`);
        if (option.setFlags) {
          for (const key of Object.keys(option.setFlags).sort()) {
            lines.push(`            $ ${key} = ${formatPythonValue(option.setFlags[key]!)}`);
          }
        }
        lines.push(`            jump ${option.target}`);
      }
      return lines;
    }
    case 'state_change': {
      const lines: string[] = [];
      for (const key of Object.keys(beat.set).sort()) {
        lines.push(`    $ ${key} = ${formatPythonValue(beat.set[key]!)}`);
      }
      return lines;
    }
    case 'jump':
      return [`    jump ${beat.target}`];
    // Canonical-only beats that have no Ren'Py rendering in v1.
    case 'stage':
    case 'panel_cue':
    case 'asset_event':
    case 'branch':
      return [];
    default: {
      const exhaustive: never = beat;
      throw new Error(`renpy: unhandled beat kind: ${JSON.stringify(exhaustive)}`);
    }
  }
}

function emitScene(scene: Scene, characters: Map<string, Character>): string[] {
  const lines: string[] = [`label ${scene.id}:`];
  for (const beat of scene.beats) {
    lines.push(...emitBeat(beat, characters));
  }
  // Fall through to the declared next scene when authored.
  if (scene.next !== undefined) {
    lines.push(`    jump ${scene.next}`);
  } else {
    lines.push('    return');
  }
  return lines;
}

/**
 * Compile the canonical project into a deterministic Ren'Py (`.rpy`) script.
 * Same input always yields byte-identical output (stable ordering, sorted flag
 * assignments).
 */
export function compileRenpy(project: Project, opts?: CompileOptions): string {
  const story = selectStory(project, opts);
  const characters = indexCharacters(project);
  const scenes = gatherScenes(story);

  const lines: string[] = [
    `# Ren'Py export — generated by @ch5me/storygen-compiler`,
    `# Project: ${project.id} — Story: ${story.id} (${story.title})`,
    `# Do not edit by hand; regenerate from the canonical story DB.`,
    '',
  ];

  lines.push(...emitDefines(project.world.characters));
  lines.push('');
  lines.push(`label start:`);
  lines.push(`    jump ${story.startSceneId}`);

  for (const scene of scenes) {
    lines.push('');
    lines.push(...emitScene(scene, characters));
  }

  return `${lines.join('\n')}\n`;
}
